config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  root 'pedidos#index'
  resources :cardapios
  resources :clientes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cardapio.rb
class Cardapio < ApplicationRecord
   belongs_to :user
   
end

app/controllers/cardapios_controller.rb
class CardapiosController < ApplicationController
  before_action :set_cardapio, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  

  # GET /cardapios
  # GET /cardapios.json
  def index
    @cardapios = Cardapio.all
  end

  # GET /cardapios/1
  # GET /cardapios/1.json
  def show
  end

  # GET /cardapios/new
  def new
    @cardapio = Cardapio.new
  end

  # GET /cardapios/1/edit
  def edit
  end

  # POST /cardapios
  # POST /cardapios.json
  def create
    @cardapio = Cardapio.new(cardapio_params.merge(user: current_user))

    respond_to do |format|
      if @cardapio.save
        format.html { redirect_to @cardapio, notice: 'Cardapio was successfully created.' }
        format.json { render :show, status: :created, location: @cardapio }
      else
        format.html { render :new }
        format.json { render json: @cardapio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardapios/1
  # PATCH/PUT /cardapios/1.json
  def update
    respond_to do |format|
      if @cardapio.update(cardapio_params)
        format.html { redirect_to @cardapio, notice: 'Cardapio was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardapio }
      else
        format.html { render :edit }
        format.json { render json: @cardapio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardapios/1
  # DELETE /cardapios/1.json
  def destroy
    @cardapio.destroy
    respond_to do |format|
      format.html { redirect_to cardapios_url, notice: 'Cardapio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardapio
      @cardapio = Cardapio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardapio_params
      params.require(:cardapio).permit(:item)
    end
end

app/helpers/cardapios_helper.rb
module CardapiosHelper
end

app/views/cardapios/_form.html.erb
<%= form_with(model: cardapio, local: true) do |form| %>
  <% if cardapio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardapio.errors.count, "error") %> prohibited this cardapio from being saved:</h2>

      <ul>
      <% cardapio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cardapios/edit.html.erb
<h1>Editing Cardapio</h1>

<%= render 'form', cardapio: @cardapio %>

<%= link_to 'Show', @cardapio %> |
<%= link_to 'Back', cardapios_path %>

app/views/cardapios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cardapios</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardapios.each do |cardapio| %>
      <tr>
        <td><%= cardapio.item %></td>
        <td><%= link_to 'Show', cardapio %></td>
        <td><%= link_to 'Edit', edit_cardapio_path(cardapio) %></td>
        <td><%= link_to 'Destroy', cardapio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cardapio', new_cardapio_path %>
<br>
<%= link_to 'Home', root_path %>

app/views/cardapios/new.html.erb
<h1>New Cardapio</h1>

<%= render 'form', cardapio: @cardapio %>

<%= link_to 'Back', cardapios_path %>

app/views/cardapios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @cardapio.item %>
</p>

<%= link_to 'Edit', edit_cardapio_path(@cardapio) %> |
<%= link_to 'Back', cardapios_path %>